# Code generated by cmd/polaris-provider-gen from apache-polaris-1.5.0. DO NOT EDIT.

resource "polaris_rest_resource" "catalog" {
  provider = polaris.management

  create_operation_id = "createCatalog"
  read_operation_id   = "getCatalog"
  delete_operation_id = "deleteCatalog"

  path_params = {
    catalogName = "risk"
  }

  body = jsonencode({
    catalog = {
      type = "INTERNAL"
      name = "risk"
      properties = {
        "default-base-location" = "s3://risk-warehouse/"
      }
      storageConfigInfo = {
        storageType      = "S3"
        allowedLocations = ["s3://risk-warehouse/"]
      }
    }
  })

  id_attribute = "name"
}
