#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

MAX_ROUNDS="${AGENT_MAX_ROUNDS:-5}"
POLARIS_RELEASE="${POLARIS_RELEASE:-latest}"
AGENT_MODEL="${AGENT_MODEL:-gpt-5.2}"
WORK_DIR="${ROOT_DIR}/.agent"
PROMPT_FILE="${WORK_DIR}/repair-prompt.md"
FAILURE_LOG="${WORK_DIR}/failure.log"
LAST_MESSAGE="${WORK_DIR}/last-message.md"

mkdir -p "${WORK_DIR}"

default_codex_command() {
  if [[ -n "${OPENAI_API_KEY:-}" ]]; then
    printf 'npx --prefix tools/agent-runtime codex exec --dangerously-bypass-approvals-and-sandbox -a never --search -m %q -C %q -o %q -' "${AGENT_MODEL}" "${ROOT_DIR}" "${LAST_MESSAGE}"
  fi
}

AGENT_REPAIR_COMMAND="${AGENT_REPAIR_COMMAND:-$(default_codex_command)}"

run_checks() {
  make generate POLARIS_RELEASE="${POLARIS_RELEASE}" &&
    make fmt &&
    make test &&
    make build || return $?

  return 0
}

write_prompt() {
  local round="$1"
  local status="$2"
  {
    echo "# Agentic Terraform Provider Repair Task"
    echo
    echo "You are running inside a GitHub Actions-style autonomous repair loop."
    echo "Goal: keep this Terraform provider compatible with the newest Apache Polaris OpenAPI specs."
    echo
    echo "Round: ${round}/${MAX_ROUNDS}"
    echo "Polaris release selector: ${POLARIS_RELEASE}"
    echo "Status: ${status}"
    echo
    echo "Hard requirements:"
    echo "- Do not remove tests to make the build green."
    echo "- Keep the provider in Go."
    echo "- Keep generated files generated by cmd/polaris-provider-gen."
    echo "- Prefer deterministic generator fixes over hand-editing generated output."
    echo "- Maintain public-repo hardening: least privilege GitHub permissions, no secrets in logs, no broad workflow permissions."
    echo "- Keep external GitHub Actions pinned to full commit SHAs."
    echo "- Keep generated provider update PR commits releasable with Conventional Commits, normally feat(polaris): ..."
    echo "- If tooling is stale, update pinned tooling intentionally and keep CI green."
    echo "- Add or update docs/adr records for durable decisions, new Polaris release behavior, workflow constraints, or test strategy changes."
    echo "- Run: make generate fmt test build."
    echo "- Stop only when all checks are green."
    echo
    echo "Recent failure log:"
    echo
    echo '```text'
    tail -n 240 "${FAILURE_LOG}" 2>/dev/null || true
    echo '```'
    echo
    echo "Current git diff summary:"
    echo
    echo '```text'
    git diff --stat || true
    echo '```'
  } >"${PROMPT_FILE}"
}

echo "Agentic Polaris provider update loop"
echo "Polaris release: ${POLARIS_RELEASE}"
echo "Max rounds: ${MAX_ROUNDS}"

for round in $(seq 1 "${MAX_ROUNDS}"); do
  echo "== Round ${round}/${MAX_ROUNDS}: generate + test =="
  if run_checks >"${FAILURE_LOG}" 2>&1; then
    cat "${FAILURE_LOG}"
    echo "All checks green."
    exit 0
  fi

  cat "${FAILURE_LOG}"
  write_prompt "${round}" "checks failed"

  if [[ -z "${AGENT_REPAIR_COMMAND}" ]]; then
    echo "No AGENT_REPAIR_COMMAND configured and OPENAI_API_KEY is not available." >&2
    echo "Set AGENT_REPAIR_COMMAND or OPENAI_API_KEY for autonomous repair." >&2
    exit 1
  fi

  echo "== Round ${round}/${MAX_ROUNDS}: running repair agent =="
  # shellcheck disable=SC2086
  ${SHELL:-bash} -c "${AGENT_REPAIR_COMMAND} < '${PROMPT_FILE}'"
done

echo "Agentic loop reached ${MAX_ROUNDS} rounds without green checks." >&2
exit 1
