# Code generated by cmd/polaris-provider-gen from apache-polaris-1.5.0. DO NOT EDIT.

data "polaris_rest_call" "catalogs" {
  provider = polaris.management

  operation_id = "listCatalogs"
}

output "catalogs_json" {
  value     = data.polaris_rest_call.catalogs.response_body
  sensitive = true
}
