# Code generated by cmd/polaris-provider-gen from apache-polaris-1.5.0. DO NOT EDIT.

terraform {
  required_providers {
    polaris = {
      source = "tsukubatexas/polaris"
    }
  }
}

variable "polaris_base_url" {
  type = string
}

variable "polaris_realm" {
  type    = string
  default = "POLARIS"
}

variable "oauth_token_url" {
  type = string
}

variable "oauth_scope" {
  type = string
}

variable "client_id" {
  type = string
}

variable "client_secret" {
  type      = string
  sensitive = true
}

provider "polaris" {
  alias    = "management"
  endpoint = "${var.polaris_base_url}/api/management/v1"
  realm    = var.polaris_realm

  oauth_token_url = var.oauth_token_url
  oauth_scope     = var.oauth_scope
  client_id       = var.client_id
  client_secret   = var.client_secret
}

provider "polaris" {
  alias    = "catalog"
  endpoint = "${var.polaris_base_url}/api/catalog"
  realm    = var.polaris_realm

  oauth_token_url = var.oauth_token_url
  oauth_scope     = var.oauth_scope
  client_id       = var.client_id
  client_secret   = var.client_secret
}
