name: Scorecard

on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "11 5 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scorecard:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: ossf/scorecard-action@62b2cac7ed8198b15735ed49ab1e5cf35480ba46 # v2.4.0
        with:
          results_file: scorecard.sarif
          results_format: sarif
          publish_results: true
