name: Test Catalog

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "43 4 * * 1"

permissions:
  contents: read

jobs:
  test-catalog:
    runs-on: ubuntu-latest
    container: golang:1.23-bookworm
    services:
      polaris:
        image: apache/polaris:latest
        env:
          POLARIS_BOOTSTRAP_CREDENTIALS: POLARIS,root,s3cr3t
        ports:
          - 8181:8181
    env:
      POLARIS_ENDPOINT: http://polaris:8181/api/management/v1
      POLARIS_REALM: POLARIS
      POLARIS_ROOT_CLIENT_ID: root
      POLARIS_ROOT_CLIENT_SECRET: s3cr3t
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3
        with:
          terraform_wrapper: false
      - run: apt-get update && apt-get install -y --no-install-recommends curl jq unzip ca-certificates
      - run: go mod download
      - run: make generate fmt test build
      - run: scripts/test_catalog.sh
